### ISSUE TITLE
Bug - Kernel versions are sorted like strings instead of integers

### ISSUE THREAD

**Issue by nikdiklic** [Octal450/J-Runner-with-Extras#13]
**Describe the bug**
Kernel versions are not properly sorted. They follow the string sorting instead of integer sorting. This would keep the newer dash versions on the bottom of the list

**Expected behaviour**
A properly sorted list would be 6717, 7371, 9199, 17489, 17559

**Screenshots**
![image](https://user-images.githubusercontent.com/14840458/155852125-f701889a-3358-49f9-b693-92a9d0119885.png)

**Comment by Octal450** [comment]
Thanks for the fix in #14 
Thank you!
Josh
