### ISSUE TITLE
Bug - Nanddump fail to load back into source

### ISSUE THREAD

**Issue by LazyITGuyTM** [Octal450/J-Runner-with-Extras#15]
**Describe the bug**
After creating a ECC, which gets loaded into source, and after writting ECC and getting CPU key, source does not auto default back to nanddump.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create ECC
2. Write ECC
3. Enter CPU key into jrunner
4. Nanddump is not loaded into source but instead the ecc file is still loaded into source.

**Expected behaviour**
Nanddump should be auto loaded back into source after getting cpu key from xell

**Screenshots**

**System (please complete the following information):**
 - OS: windows 10
 - Version: latest at the time of writing.

**Additional context**

**Comment by Octal450** [comment]
That is only a problem with some nand flasher devices and is already fixed in the next branch. If you want to test it ahead of public release, compile the exe.

Kind Regards,
Josh
