### ISSUE TITLE
Picoflash wont read nands 4gb and 16mb

### ISSUE THREAD

**Issue by gamersuno22** [Octal450/J-Runner-with-Extras#16]
When I try to read some nand the program freezes and the following comes out. 

Windows 10 updated

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.TimeoutException: Se excedió el tiempo de espera de la operación.
   en System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   en System.IO.Ports.SerialStream.Read(Byte[] array, Int32 offset, Int32 count)
   en System.IO.Ports.SerialPort.Read(Byte[] buffer, Int32 offset, Int32 count)
   en JRunner.PicoFlasher.RecvUInt32(SerialPort serial)
   en JRunner.PicoFlasher.getFlashConfig()
   en JRunner.MainForm.xPanel_getmb()
   en JRunner.Panels.XeBuildPanel.btnGetMB_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4470.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
JRunner
    Versión del ensamblado: 3.1.2.0
    Versión Win32: 3.1.2.0
    Código base: file:///D:/Program%20Files%20(x86)/Xbox%20360/J-Runner%20with%20Extras/JRunner.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4488.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4488.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml

**Comment by Octal450** [comment]
Drivers installed?
I'll try to catch the error.

Kind Regards,
Josh

**Comment by gamersuno22** [comment]
I just found the problem, there is a diagram on the internet that has 2 pins reversed.

**Comment by Octal450** [comment]
Alright, thank you brother.
I will still try to catch the error and display a message.

Kind Regards,
Josh

**Comment by tadaskarpavicius** [comment]
> I just found the problem, there is a diagram on the internet that has 2 pins reversed.

Hey @gamersuno22 , would you mind sharing which pins were reversed? I am having the same error and checked and tried everything, but can't read the nand
