### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by dolphin22** [Octal450/J-Runner-with-Extras#17]
**Describe the bug**
Mismatched nanddump1.bin and nanddump2.bin on Corona16MB with PicoFlasher ver v3.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on "?" -> 
Checking Console...
0x00043000
Corona 16MB
2. Click on "Read Nand"
Reading Nand to C:\Users\xxx\Downloads\XBox360\J-Runner with Extras\output\nanddump1.bin
Read Successful!

Initializing nanddump1.bin, please wait...
Nand Initialization Finished

Reading Nand to C:\Users\xxx\Downloads\XBox360\J-Runner with Extras\output\nanddump2.bin
Read Successful!

[Mismatched]
Comparing...
0x0064
0x01C2
0x027C

**Expected behaviour**
nanddump1 and nanddump2 should match???

**Screenshots**
[https://i.imgur.com/Knr11TP.png](https://i.imgur.com/Knr11TP.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version: 

**Additional context**
Try several times but still same results. Files can be downloaded here **https://drive.google.com/file/d/1cQZZdQE--L_KZ30BhShLpAOsW3GKwRKx/view?usp=sharing**

**Comment by Octal450** [comment]
Not a bug. If the dumps don't match, something about your setup is wrong.

Kind Regards,
Josh

**Comment by dolphin22** [comment]
> 

thanks, I will double check

**Comment by dolphin22** [comment]
confimed, it's bad wirings and/or wire are too long for stable reading. Thanks!
