### ISSUE TITLE
Feature Request - Builds for Linux & MacOSX using Mono

### ISSUE THREAD

**Issue by OCsonic** [Octal450/J-Runner-with-Extras#21]
**Is your feature request related to a problem or missing feature? Please describe.**
There are no native Linux or MacOSX builds of J-Runner w/ Extras

**Describe the solution you'd like**
J-Runner w/ Extras builds using the Mono .net implementation.

**Comment by Octal450** [comment]
No plans for other OS support at this time, reasoning: J-Runner is a Windows native application, and all the hardware device drivers are Windows drivers, and lastly dependent programs such as XeBuild are Windows programs.

Kind Regards,
Josh
