### ISSUE TITLE
Feature Request - Windows Vista support

### ISSUE THREAD

**Issue by ClosetPErv** [Octal450/J-Runner-with-Extras#23]
I have always ran my Jrunner on an old Vista computer but with the latest update the program just stops working. I do love my old Vista laptop, is there some way to make it compatible? Thanks for everything 360 these last years, it has been a blast!

**Comment by Octal450** [comment]
Hi,
There is native Vista support. 

You need Vista Service Pack 2 with dotNET Framework 4.5.2 installed. 

It is recommended to have the updated as well however the application seems to work on RTM. 

Can you look for a file called Error.log in the same folder as the executable? That might help to narrow down why it’s crashing. 

Kind Regards,
Josh

**Comment by ClosetPErv** [comment]
Yep, .NET was indeed the issue. I really thought I had downloaded all dotNET there would ever be for that old computer, but I was wrong :)
Thanks for helping me out, now it works flawlessly again!

**Comment by Octal450** [comment]
My pleasure, glad you got it working!

Kind Regards,
Josh
