### ISSUE TITLE
Bug - Crash on Create  XeBuild

### ISSUE THREAD

**Issue by SSGMCCUE147** [Octal450/J-Runner-with-Extras#24]
trying to RGH a Trinity with a aceV3 i am able to do everything tell i get to the point i have to create the XeBuild. it crashes no mater what i do and in compatibily mode 
[Error.log](https://github.com/Octal450/J-Runner-with-Extras/files/9473974/Error.log)

**Comment by Octal450** [comment]
Not a bug. Access is denied errors, basically an antivirus or something is accessing the files while you try to use it. Please exclude JR from antivirus such as Windows Defender, etc.

I will look into catching the bug more gracefully.

Kind Regards,
Josh

**Comment by SSGMCCUE147** [comment]
Thank you I will do that and get back to you

**Comment by SSGMCCUE147** [comment]
That was the issue. I feel like an idiot now. Thank you for your time

**Comment by Octal450** [comment]
No problem. Glad you got it working!

Kind Regards,
Josh
