### ISSUE TITLE
Bug - convert to RGH3 crashes on 32bit windows

### ISSUE THREAD

**Issue by AR1972** [Octal450/J-Runner-with-Extras#27]
**Describe the bug**
Both the J-Runner and the standalone convert to RGH3 application crash on 32 bit windows, I think targeting
the .net components to x86 will solve this issue. I use a Lenovo 100s laptop at my workbench because of it's
small size but it is only supported by Window 10 32 bit because of a weird 32 bit only EFI.

I have confirmed this bug to exist on 32 bit  Windows 7 also, both applications work as expected on 64 bit
Windows 7 and 10.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
crash.txt
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at RGH2_to_3_GUI.RGH2to3.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RGH2 to 3 GUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Adam/Desktop/RGH2To3/RGH2%20to%203%20GUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Octal450** [comment]
Hi,
That's odd. J-Runner with Extras targets .NET Framework 4.5.2 x86.

The standalone app has NOTHING to do with J-Runner, and the standalone app still uses python if I recall correctly.

Please attach a crash report from J-Runner with Extras, rather than that standalone program. I can't help with that program because I have nothing to do with it.

In the meantime, I'm going to go look for a 32 bit machine to test on, if I don't find, I'll spin up a VM.

Kind Regards,
Josh

**Comment by Octal450** [comment]
No problem in J-Runner with Extras here.

![image](https://user-images.githubusercontent.com/25598604/196070096-bb4e18d1-a8df-4210-a984-35dbc139840d.png)

Kind Regards,
Josh

**Comment by AR1972** [comment]
I can't recreate the problem with J-Runner anymore, I think windows was locking the update.bin file,
I was getting a system.io exception and unauthorized access exception with J-Runner. gonna blame
this one on Windows.

**Comment by AR1972** [comment]
I got it to happen again, copy and paste update.bin to desktop, load with j-runner then convert to RGH3.
I think windows is preforming a file scan in the background, causing this issue. I initially thought it was 
a 32 bit issue because both applications were failing only on 32 bit systems.

![2022-10-16](https://user-images.githubusercontent.com/2080288/196072154-d8beaf64-6e7d-4c61-b664-a60f2417e094.png)

**Comment by Octal450** [comment]
Try excluding the J-Runner with Extras folder from Defender and restarting.

Kind Regards,
Josh
