### ISSUE TITLE
Bug - cannot make rgh3 conversion

### ISSUE THREAD

**Issue by Leerz** [Octal450/J-Runner-with-Extras#28]
**Describe the bug**
i'm updating an old modification -  slim corona and fats

dumped the nand with Simple 360 NAND Flasher ,
imported the dump on jrunner and it will not make a new xebuild image it says "Converting Image to RGH3...
Failed: The image is either already RGH3, or an unsupported image type"

**To Reproduce**
Steps to reproduce the behaviour:
1. dump nand (lower dash)
2. ftp over output folder (flashdmp and cpukey)
3. import on jrunner , click rgh3 see error
KV type   : type2 (hashed - unchecked, master key not available)
---------------------------------------------------------------
    xeBuild Finished. Have a nice day.
---------------------------------------------------------------
Converting Image to RGH3...
Failed: The image is either already RGH3, or an unsupported image type

**Expected behaviour**
it converts like normal

**Screenshots**

**System (please complete the following information):**
 - OS: win10
 - Version:  21h2/1904.2251

**Additional context**
i convert the image from the original script and it works just fine.

**Comment by Octal450** [comment]
Please send me the nand dump. I don't have this problem.
<redacted>

Kind Regards,
-Josh

**Comment by Leerz** [comment]
> btw,  i sent the file thank you for looking into it.

also,
absolutely strange, got the latest update now and it's working , 
previous logs doesn't show the failed rgh3 conversion attempt, BUT, i have redone the console dumps that i manually converted to rgh3 (when they failed) and jrun now converts it just fine. 

strange enough, even if i rebuilt an already converted rgh3 file it doesn't say the error above. 

i'll be on the lookout if it happens again

Thank you for keeping jrunner great everyday :)

**Comment by Octal450** [comment]
Interesting, thanks for the feedback! I will look ingo it.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Wrote you back. Can't download the file you sent.
-J

**Comment by Octal450** [comment]
Closing as I've had no response for 3 weeks.

Josh
