### ISSUE TITLE
Bug - Jasper Big block RGH3 issue

### ISSUE THREAD

**Issue by Nightmare090** [Octal450/J-Runner-with-Extras#29]
**Describe the bug**
 Hello Octal450
Thank you for amazing job with J-runner with extras. But I found a bug with Big block 512mb jasper. 
Everything works until you try to write BB (64mb) nand. Instead of 15 min write time it will finish in 3 min (like 16mb nands do).
When you write this nand with older j-runner version, it will write full BB 64mb nand and console works. 

This problem occurs with XeBuild image and stock nand too. I didn't try any other BB nands or 48mb(corona 4gb) nands yet.
I found it immediately as I saw write time. But there are a lot of other not so experienced people out there, that won't notice something is wrong. I hope you can fix that in latest update.

If you need some additional info or nand dump, feel free to contact me.
Have a nice day.

Nightmare0

**Comment by Octal450** [comment]
Hi,
What device are you trying to write with?

Kind Regards,
Josh

**Comment by Nightmare090** [comment]
Hello
I am using JR-P v2 for many years without any issues.

**Comment by Octal450** [comment]
hi,
Thanks, I'll look into it.

-J

**Comment by Octal450** [comment]
Confirmed. Fix is on the way.

J

**Comment by Nightmare090** [comment]
That was fast. Do you need to test it? I still have that console.

**Comment by Octal450** [comment]
I'll message you once I send the release out. Few little bugs to squash.

J

**Comment by Nightmare090** [comment]
If I will still have that console I will test it for you. Nevertheless, good job. Have a nice day.

**Comment by Octal450** [comment]
It will be within the next few hours. Can that work?

You too!
J

**Comment by Nightmare090** [comment]
It's 0:20 here. Going to work at 6. If you don't mind, I would do it tomorrow after work.

**Comment by Octal450** [comment]
That is fine, thank you! 

J
