### ISSUE TITLE
Bug - Trinity write issue

### ISSUE THREAD

**Issue by Nightmare090** [Octal450/J-Runner-with-Extras#30]
Hello Josh

Like last time with Jasper BB, I think there is another write issue with Trinity.

This week I was doing two trinity upgrade from RGH2-->RGH3
First one was quick and easy, because I dumped NAND in console with Simple nand flasher, created new RGH3 XeBuild image and wrote back with simple nand flasher. After that I reworked installation and everything worked.

With second Trinity I forgot to write new XeBuild image and desoldered old CR3. Never mind... I made RGH3 conversion, wrote new XeBuild with JR-P v2 and... nothing. Console turns off one second after power on. After few hours of resoldering, I tried to install CR3 back. Didn't work. No green light. cpu_rst was working and reseting, post_out was working (even tried postfix adapter). Both checked with multimeter.
Tried CR4 XL and Ace v3 as well. No green light, could't get console to boot. 
With each modchip I tried XeBuild and .ecc with no success.

After all this shit I tried to build Trinity RGH3 .ecc in your latest build (V3.2.1 r3) and wrote it with older J-runner version.
Started up, console didn't turned off this time, installed RGH3 and got Xell
Created XeBuild from first nand dump and console is working.

Sorry for wall of text. But I wanted to describe you why I assume there is something wrong with Trinity writing with JR-P v2

Now I have two more stock Trinity boards, not conversions. So I will do two new installs.

If there is any way I can help you to find this bug, tell me how.

David

**Comment by Octal450** [comment]
Hi David,
Test on my Trinity with JR-P V2 with RGH3 XeLL and also XeBuild. Write and console turns on no problem.

Console turns on then off after 1 second = You have not correctly soldered the POST or PLL wires for RGH3. Maybe a dodgy connection.

For now I am not marking as an issue as everything seems ok on my end. Please retry.

Kind Regards,
Josh
