### ISSUE TITLE
Bug - cannot create 6717 RGH3 corona image

### ISSUE THREAD

**Issue by selective5296** [Octal450/J-Runner-with-Extras#32]
**Describe the bug**
I am trying to create an xebuild image of dashboard 6717 on a corona RGH3.

I dumped the nand with the xell reloaded web interface, then loaded it into jrunner but whenever I try to create a 6717 xebuild image it errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. download nand using the xell web interface (eg: 192.168.???.??)
2. load in jrunner
3. change xebuild Kernel Version to 6717
4. click Create XeBuild
5. error in output

`The specified console bootloader list (coronabl) is missing from the ini (D:\J-Runner-with-Extras\xeBuild\6717\_glitch2.ini)`

![image](https://user-images.githubusercontent.com/43064195/208231510-a429998c-d5c1-48de-8c0b-8b9365dd51db.png)

OS: win10
Version: 21h2

**Additional context**
9199 works fine.

**Comment by Octal450** [comment]
6717 kernel is not supported on slim consoles.

Kind Regards,
Josh
