### ISSUE TITLE
Bug - skipping xell when making a 17489 dev xebuild

### ISSUE THREAD

**Issue by EnekoT2001** [Octal450/J-Runner-with-Extras#33]
**Describe the bug**
Every time i try to build an XDK nand XeLL gets skipped. it says "WARNING: skipping xell, there doesn't appear to be enough room!", i've tried with the dump of my nand before i made any modifications and with a dump of the nand i made after making a retail 17559 xebuild. Is this intended or a bug? it makes switching from xdk to retail more annoying and no way to recover from a softbrick without hardware flashing it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load any nand dump as source
2. Choose kernel version 17489 on options
3. Click create xebuild
4. The warning appears just after it start to build

**Expected behaviour**
No warning and xell working on the kay combination at boot like it does on 17559

**Screenshots**
not needed imo

**System (please complete the following information):**
 - OS: Windows 11 22621.963
 - Version: Jrunner 3.2.2

**Additional context**
A bit off topic but ive found a related bug to this: i cannot change region of the development environment, every time i try it reboots and it stays on europe, i even tried manually changing it on xebuild before creating it and nothing, its not really important tho.

**Comment by Octal450** [comment]
Not a bug.
XeLL is not included in XDKbuild. The message is from XeBuild not J-Runner itself so I can't supress it.

Also, I doesn't know what you mean by recover from brick. You can reflash via hardware.

I will ask Xvistaman next time I speak to him about XeLL and also the region and if I find anything I will reply back.

Kind Regards,
Josh

**Comment by EnekoT2001** [comment]
I see, I thought that’d be the case but some ppl told me it might be a bug of jrunner, i haven’t personally tried to do it on xebuild separately so wanted to submit it here just in case.

I know it can be flashed by hardware, I mentioned it, it’s just that if there’s a softbrick of some kind it will require to hardware flash it whereas by having XeLL it can be fixed easily, that’s the only reason I was worried about it. Thank you for answering and for making this amazing software

**Comment by Octal450** [comment]
Thanks. Sadly due to how XDKbuild works it needs more space on the flash than normal image.

Thanks for your kind words! My pleasure.

Kind Regards,
Josh
