### ISSUE TITLE
Feature Request - Document Tigard Compatibility

### ISSUE THREAD

**Issue by melvyn2** [Octal450/J-Runner-with-Extras#34]
**Is your feature request related to a problem or missing feature? Please describe.**
The [Tigard](https://github.com/tigard-tools/tigard) is an FTDI-based hardware multitool. J-Runner detects this as a X-Flasher in SPI mode, and with the correct wiring this board can be used to read/write the 360 nand just like the original X-Flasher. It would be useful for some who already have such hardware to know how to use it to flash their 360.

**Describe the solution you'd like**
Document somewhere the possibility and method of using a tigard to flash (possibly just linking here).

**Additional context**
1. Plugging in the Tigard should cause J-Runner to recognize an X-Flasher in SPI mode.
2. Ensure the Tigard is set to V3.3 mode and SPI/JTAG mode rather than SWD/I2C mode.
3. Connect the SPI breakout cable to the 1x8 pins (NOT the 2x4 specifically-designated SPI pins, as these use the second 'B' interface of the tigard)
4. Connect the GND, SCK, CS, CIPO, and COPI leads to their labeled wires.
5. Connect the SMC_DBG_EN (J2C3 Pad 6) to the wire labeled SRST, and SMC_RST_XDK_N (J2C3 Pad 5) to the wire labeled TRST (guessed, this worked first try).
6. Use J-Runner as if using a normal X-Flasher.

Pic of my awful setup:
![IMG_4456](https://user-images.githubusercontent.com/9157412/212577212-449f30d8-aff3-4fef-8744-6521a7452752.jpeg)
I don't have any eMMC/4G boards to test the other mode on.

**Comment by Octal450** [comment]
Hi,
If it's detected as an xFlasher SPI, then what is missing in order to make it work?
Josh

**Comment by melvyn2** [comment]
Nothing, I simply wanted to publicly document this as working for others to use.
Edit: if there's a better place to post this I'd be happy to move this there.

**Comment by Octal450** [comment]
Hi,
Ah ok. I'll think about where the best place would be. Perhaps a readme should be created listing all tested supported devices.

However since it isn't a change in the application , I will close the request.

Kind Regards,
Josh
