### ISSUE TITLE
Bug - Hey Josh tony Here pico flasher is getting a misread on trinity consoles. I am getting header wrong when i use a jrunner there is no problems but obviously there is a problem with the header dump on the pico flasher

### ISSUE THREAD

**Issue by darkhorseman45** [Octal450/J-Runner-with-Extras#35]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version: 

**Additional context**

**Comment by Octal450** [comment]
1) Please fill out the template properly if you report a bug
2) That's not a J-Runner issue, it's an issue with your wiring, soldering or the Pico itself.

Kind Regards,
Josh
