### ISSUE TITLE
Bug - Not working with Demon 

### ISSUE THREAD

**Issue by wesk1** [Octal450/J-Runner-with-Extras#36]
**Describe the bug**
Im using the TX demon, it allows me to have dual nand and read/write to them via usb.

**To Reproduce**
I click Read Nand. it gives me Device Not found

**Expected behavior**
I should be able to read my nand using the tx demon, i tried with an old version of jrunner that is working fine.

**Screenshots**
![error](https://user-images.githubusercontent.com/518983/215920410-e5aa7ca3-4409-425c-897b-45e2d3b5faea.png)

**System (please complete the following information):**
 - OS: win10
 - Version: 21H2

**Additional context**
none

**Comment by wesk1** [comment]
disregard, it started to work just waited a bit longer.

**Comment by Octal450** [comment]
Alright, let me know if you notice any issues.

J
