### ISSUE TITLE
Feature Request - Show target IP address in console when "Scan IP Range"

### ISSUE THREAD

**Issue by shooter556** [Octal450/J-Runner-with-Extras#37]
Hi Josh,

Thank you for your improved J-runner. I've been using this tool always.

For some reason, when booting into Xell-reloaded for the 1st time after writing ecc into NAND, my monitor just shows a blank screen.
(Finally the Xell-reloaded is the culprit, I'm quite sure of that.)

So every time I boot xbox360 I use "Scan IP Range" to get CPU key.

Though cpu key can be fetched eventually, but the target IP address J-runner scanned is nowhere to know.

Can you please let J-runner shows target IP address in console when finished scanning?

**Comment by Octal450** [comment]
Glad it's helping you out.
To confirm - you're asking if I can add an output that shows the IP number it found when the scan finds a system?

-J

**Comment by shooter556** [comment]
Yes, that will be a great help. I just want to know the exact IP address J-runner has found out in console when scanning.

**Comment by Octal450** [comment]
![image](https://user-images.githubusercontent.com/25598604/230645091-f788dc54-a355-4747-9876-277fc348dd52.png)


-J

**Comment by shooter556** [comment]
Brilliant! Looks nice and effective.

**Comment by Octal450** [comment]
Implemented and completed checkout in version next.
Thanks for your suggestion! It will be included in the next release (soon).

Kind Regards,
josh
