### ISSUE TITLE
Bug - no boot when flashing xell for Xenon Jtag. (PicoFlasher) Nand reads and writes are successful and i am able to flash back to retail. I double checked all diodes and wires. 

### ISSUE THREAD

**Issue by GFLTech** [Octal450/J-Runner-with-Extras#39]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Version: 

**Additional context**

**Comment by Octal450** [comment]
Not a bug with the application.

Also, if you expect help, you need to fill out the template!

Kind Regards,
Josh
