### ISSUE TITLE
Bug - Potential Minor NAND Corruption when Generating XeBuild Images from Dumps

### ISSUE THREAD

**Issue by byt3swap** [Octal450/J-Runner-with-Extras#40]
**Describe the bug**
Across 5 different 360s that I have performed RGH on over the past year or so (some 1.2, some 3.0), I'm seeing the same visual text glitching on the main menu after flashing XeBuild images (kernel 17559) created from NAND dumps from the console.  When scrolling through the menu items, letters in the settings listing will be swapped with different characters for a few frames, returning back to the correct characters after.  Creating a donor NAND with the extracted keyvault and SMC config, then flashing through xell, causes this issue to go away.  XeBuild images created from dumped NAND also show this issue when flashed through xell. Multiple dumps of each NAND have been taken, and compared, and are identical. This occurs across multiple displays at all available resolutions.

**To Reproduce**
1. Dump console NAND (picoflasher was used for all NAND dumps)
2. Flash xell + get CPU key
3. Generate XeBuild image from NAND dump
4. Flash using NAND flasher or from xell
5. Go to 'Console Settings' on dashboard, scroll up and down through settings
6. Characters will 'swap' with other characters

**Expected behaviour**
Scrolling through console settings should not exhibit text glitches.

**System (please complete the following information):**
 - Console/RGH Revisions: Jasper (Kronos) RGH3, Jasper (Kronos) RGH 1.2, Falcon (RGH 1.2) Corona (4GB) RGH3

**Additional context**
As far as I can tell, no core functionality is altered, but would like to report this in case some corruption of the NAND may lead to other issues down the line. Potentially an issue with dumping via picoflasher, but I doubt it is an issue with the systems since it seems to be so easily reproducible across different units.

**Comment by Octal450** [comment]
Negative - this is NOT the fault of the application. You are either damaging the units during the process, or the corruption is occurring due to poor solder/other Pico issues (it's been a problematic device, sadly not on JR's end to fix).

The fact that donor nand fixes it means your nand dumps are bad. Another common Pico issue.

I recommend getting a better programmer, like an xFlasher.

Kind Regards,
Josh

**Comment by byt3swap** [comment]
Thanks. I was not aware of these possible issues with the pico, but figured it a possibility.  Definitely not a soldering issue and I'm unaware of any reason hardware wise that the pico shouldn't be sufficient for doing proper SPI NAND reads/writes.  I'll dig though their code when I have a chance and compare against dumps taken through other means, as it's interesting that this same minor error has occurred for me across so many consoles, and is also one that could go easily missed.

Best,
byt3swap
