### ISSUE TITLE
Feature Request - Include Corona Keys fix xeBuild patch

### ISSUE THREAD

**Issue by InvoxiPlayGames** [Octal450/J-Runner-with-Extras#43]
On Corona RGH images, certain keys related functions don't work properly (notably XeKeysSetKey for title keys, meaning games that use it for decryption don't work, e.g. Rock Band games suffer from the "no preview audio"/"endless loading" bug). I made a patch for this, and it would be useful to have an XeBuild option in the GUI, or to enable by default when building Corona freeboot 17559 images.

The patch in hex format:

```
00003B8C 00000001 389F0010
0000611C 00000001 387C0010
```

This bug is caused by, somewhere and somehow, the 1BL key copy at 0x16510 (17559) being blanked out on Corona. I've mitigated this issue by patching HvxKeysSetKey (for title keys) and HvxKeysExecute to instead direct those reads to the first 1BL key copy at 0x163F0 (17559). ~~I haven't been able to extensively test this on actual Corona hardware, so that is definitely something that needs doing before implementing.~~ (I have since had a friend test on Corona and can confirm the Rock Band issue is fixed.) There could also be other places the bad copy is used, but it looks like they're in firmware update routines so aren't needed.

I'd have submitted a pull request, but I can't seem to get J-Runner to want to build, and I'm not sure whether it would be best to have this as an option that has to be enabled, or to enable it by default when building Corona images.

**Comment by Octal450** [comment]
Thx. Will address this in December when I'm home.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Done.
