### ISSUE TITLE
Bug - XL HDD

### ISSUE THREAD

**Issue by Fredward-85** [Octal450/J-Runner-with-Extras#47]
**Describe the bug**
After  building  a XE nand file selecting XL HDD for a JTAG unit the Internal hard drives no longer load after the nand update. Getting a black screen or XBOX360 lock up on boot screen with no error messages. This issue happened after Jrunner updated to latest version with updated XL HDD patches.  Tried using non XL HDD  and reflashed and my other internal hard drive worked fine.  Tried a 4TB and 8TB SSD drives and reformatted with XL HDD on FatXplorer tool and tried again with the XL HDD patch nand with same results on current version of JRunner.

**Expected behaviour**
XL HDD patch should boot hard drives over 2TB after being formatted with FatXplorer tool

**System (please complete the following information):**
 - OS: Windows 11
 - Version: V3.3.0 r2

**Additional context**
I can confirm i used another JTAG xbox 360 console with XL HDD patches does not work from Jrunner version: V3.3.0 r2

**Comment by Octal450** [comment]
I am in touch with Eaton about this. The last update fixed JTAG issues before, so I do not understand. I will let you know.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Fixed in version next. Thanks.

Kind Regards,
Josh
