### ISSUE TITLE
j-runner w10 not launching

### ISSUE THREAD

**Issue by ABU3BGE** [Octal450/J-Runner-with-Extras#49]
i try launching it in windows xp and 7 and 8 mode didnt launch 
i see it in task manager open and close

**Comment by Octal450** [comment]
Thanks for NOT filling out the template. As a result, closing this.

Make sure your dotNET 4.5.2 is installed.

Kind Regards,
Josh

**Comment by ABU3BGE** [comment]
> Thanks for NOT filling out the template. As a result, closing this.
> 
> Make sure your dotNET 4.5.2 is installed.
> 
> Kind Regards, Josh

im new to github 
 dotNET 4.5.2 is already installed
and i have latest mvsc++ ver

**Comment by Octal450** [comment]
When you open a issue, the template is already there. Don't delete it, just fill it out.

What language is your OS in?

Kind Regards,
Josh

**Comment by ABU3BGE** [comment]
> When you open a issue, the template is already there. Don't delete it, just fill it out.
> 
> What language is your OS in?
> 
> Kind Regards, Josh

arabic
