### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by duckmansweb** [Octal450/J-Runner-with-Extras#53]
**Describe the bug**
Upon loading J runner 3.3.0 r3 the software hangs at the "checking for updates" splash screen for two minutes every times it launched
Program is run as administrator, problem started with the last update 

**To Reproduce**
Steps to reproduce the behaviour:
Launch the program

**Expected behaviour**
To not hang for so long

![Captuwwre](https://github.com/Octal450/J-Runner-with-Extras/assets/162928502/b42565b0-1c19-40da-aa85-a6da72727125)

**System (please complete the following information):**
 - OS: windows 10 Pro - Test mode
 - Version:  10586

**Comment by Octal450** [comment]
This occurs when your antivirus and firewall interrupts the connection. If you’re using a VM either disconnect internet or make sure it’s set up right. 

Also that windows is very old and I’ve never tested in it. Please update to newer versions of windows. Make sure the latest updates for dot net framework 4.5.2 are installed. 

Anyways this isn’t a bug, but an issue with your network setup. Maybe I can add a timer to make it time out after 15 seconds later. 

Kind Regards,
Josh
