### ISSUE TITLE
Bug - Xenon JTAG XeLL creation seems wrong

### ISSUE THREAD

**Issue by emukidid** [Octal450/J-Runner-with-Extras#54]
**Describe the bug**
I believe the Xenon XeLL generated image is incorrectly generated or written incorrectly by PicoFlasher

**To Reproduce**
Steps to reproduce the behaviour:
1. Read Nand
2. Create XeLL
3. Write XeLL
4. Doesn't boot.
5. If I read back the NAND from this point in J-Runner and overwrite the first section (0x14A000) with the contents of xenon.bin directly in a HEX editor and write this NAND, then it will boot XeLL. There were differences in the NAND's after I did this so it wasn't writing a clean xenon.bin, I suspect something is going wrong here?

I posted on Reddit about it because others were also having the same issue: https://www.reddit.com/r/360hacks/comments/1al3b2t/comment/kv52y66/?utm_source=share&utm_medium=web2x&context=3

**Comment by Octal450** [comment]
Sorry for the late reply. I am looking into this.

**Comment by emukidid** [comment]
No problem, my reddit comment never got approved it seems so it's missing but it's basically the same writeup.

**Comment by Octal450** [comment]
The difference in files is because Create XeLL patches in the keyvault. I'm not sure right now why that's breaking it, I don't recall changing that from the older releases where it worked. It's hard to debug without a X360 with me, but I'm looking into it.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Creation of the XeLL file is correct. Writing it causes the problem. Writing the created file using the Advanced -> Nand Functions, Write, 16, Run works correctly.

Investigating.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Still investigating.

**Comment by Octal450** [comment]
If I send you a test build can you test it for me?

**Comment by emukidid** [comment]
I'm not sure when I'd get around to it sorry. I've sold off those JTAG'd Xenon consoles.

**Comment by Octal450** [comment]
OK well it's working here now so I'm closing this issue.
