### ISSUE TITLE
Bug: Patches deselected if "Both XL" patch is selected

### ISSUE THREAD

**Issue by ElecTriX666** [Octal450/J-Runner-with-Extras#57]
### Describe the bug

If selecting "Both XL" under "Drive patches" and options "UsbdSec" and "Key Fix" under "Other patches" then trying to Create XeBuild the "Other patches" are deselected, but only if "Both XL" has been selected.

This behavior makes it uncertain if other patches has been applied or not.

### To Reproduce

1. Load source
2. Select "Both XL" and both patches under "Other patches"
3. Create XeBuild
4. Click OK on prompt asking about "Both XL"
5. Other patches has been deselected according to console

### Expected Behavior

Other patches should not be automatically deselected after build if "Both XL" has been applied.

### Screenshots

Before creating XeBuild:
![image](https://github.com/Octal450/J-Runner-with-Extras/assets/35463138/412f6f5d-7457-495a-af44-23022d78262b)

After creation:
![image](https://github.com/Octal450/J-Runner-with-Extras/assets/35463138/59caca58-921a-4239-87dd-5d410b7af942)

### System version

Windows 11

### J-Runner version

3.3.0 r3

### Additional context
```
Console log
Initializing updflash-17599.bin, please wait...
Glitch2 selected
RGH3 selected
Nand Initialization Finished
Both XL selected
UsbdSec selected
Corona Key Fix selected
XeBuild Initialized
Kernel Selected: 17559
KV Info saved to file
---------------------------------------------------------------
     xeBuild v1.21.810
---------------------------------------------------------------
base path changed to C:\Users\Rob\Downloads\J-Runner-with-Extras_2\xeBuild
---- { Image Build Mode } ----
building glitch2 image

done! fsroot found ok!
---------------------------------------------------------------
C:\Users\Rob\Downloads\J-Runner-with-Extras_2\#\updflash.bin image built, info:
---------------------------------------------------------------
Kernel    : 2.0.17559.0
Console   : Corona
NAND size : 16MiB
Build     : Glitch (v2)
Xell      : power on console with console eject button
Serial    : #
ConsoleId : #
MoboSerial: #
Mfg Date  : 11/21/2013
CPU Key   : #
1BL Key   : #
DVD Key   : #
CF LDV    : 3
KV type   : type2 (hashed - unchecked, master key not available)
---------------------------------------------------------------
    xeBuild Finished. Have a nice day.
---------------------------------------------------------------
Converting Image to RGH3...
RGH3 Conversion Finished!
Saved to C:\Users\Rob\Downloads\J-Runner-with-Extras_2\#
Image is Ready
Initializing updflash.bin, please wait...
Nand includes Both XL patches
UsbdSec deselected
Corona Key Fix deselected
Nand Initialization Finished
```

**Comment by Octal450** [comment]
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at JRunner.Nand.PatchParser.getPatches(Byte[] data) in D:\Scratch\J-Runner-with-Extras\J-Runner\Nand\PatchParser.cs:line 53
   at JRunner.Nand.PatchParser.parseAll(Int32 i) in D:\Scratch\J-Runner-with-Extras\J-Runner\Nand\PatchParser.cs:line 158
   at JRunner.MainForm.nandinit(Boolean nomove, Boolean dontUpdateHackType) in D:\Scratch\J-Runner-with-Extras\J-Runner\MainForm.cs:line 2088

That's why. Fixing.

**Comment by Octal450** [comment]
Fixed.

Kind Regards,
Josh
