### ISSUE TITLE
Add support for Trinity motherboard

### ISSUE THREAD

**Issue by innobmc** [Octal450/J-Runner-with-Extras#59]
First i should admit am expert in rhg3 i have done phats, slim S and slim E am familia with alot of mother boards and their ram chips around gpu.

Common ram chips are samsung and some with NNNN kind few are winbound, now i came across a new ram(sorry i got new phone so the photo of it is gone with old 4n but the dump is in pc i will send for review) it was on trinity mother board, when i wrote xell to this console it didnt boot to xell, i tried bothe 10k and 3k resistor but nothing, its what triggered me to check what is new with this console compared to others its when i saw that the ram chip is of different kind. Am like mayb these needs a new tab as it is with winbound chips to be successfull and boot to xell.

I will add link to my drive below since we cant send dumpfiles here, i doh know if the dump alone will be enough otherwise i sent back the console to the owner, if its a must i can try to ask it back tho its miles away, but yah mayb from the dump you will be able to get the info of the ram chip and make it work with rhg3 as it is with winbound chips in your next release thanks

https://drive.google.com/file/d/14L7fg9WLOX47tMyyS-Dn7PB_-RLaU_Sb/view?usp=drivesdk

**Comment by Octal450** [comment]
You didn't do a single thing the template asks you to do. And you didn't include any info about the RAM type you're talking about so how I can know?

Also, all Trinity RAM type are fully supported. Samsung, Elpida, Hynix.

Winbond 2J is only used on Waitsburg Corona and doesn't need any patches. Winbond 2K is only used on Stingray Corona and does need WB 2K patch. All supported but these do not apply to Trinity.

I hate nonsense by the way.

Kind Regards,
Josh

**Comment by Octal450** [comment]
Also please write clearly next time I nearly had a stroke trying to understand you.

Kind Regards,
Josh
