### ISSUE TITLE
I'm not able to extract the nand from the 4gb corona with picoflasher

### ISSUE THREAD

**Issue by davbrasan** [Octal450/J-Runner-with-Extras#60]
### Describe the bug

Log:
Checking Console...
Corona: 4GB (eMMC connected)
PicoFlasher has encountered an error
Try to unplug and replug the device
System.TimeoutException

### Expected Behavior

Any solution?

### System version

Windows 10

### J-Runner version

Last Version

**Comment by Octal450** [comment]
Not a JR bug. Pico fw issue.
