### ISSUE TITLE
Bug: Reads but does not write Trinity mobo with picoflasher

### ISSUE THREAD

**Issue by XanderStrike** [Octal450/J-Runner-with-Extras#62]
### Describe the bug

I can read NAND, create XeLL, but writing XeLL fails every time.

### To Reproduce

1. Solder up RGH 3 and Raspberry Pi Pico as described for Trinity motherboards as described in [this guide](https://xbox360hub.com/guides/rgh-3-guide/)
2. Install [PicoFlasher 3.0](https://github.com/X360Tools/PicoFlasher/releases/tag/3.0) on the pico (or 2.0, neither work)
3. `?` button identifies console `Flash Config: 0x00023010 Jasper, Trinity: 16MB`
4. Read NAND 2x, succeeds, comparison succeeds, selects glitch and RGH values
5. Create XeLL, succeeds immediately
6. Write XeLL

### Expected Behavior

XeLL is written and I can proceed.

### Screenshots

```=================================================================
J-Runner with Extras
Session: 07/28/2024 20:04:06
Version: 3.3.0 r3
Status: Up to date

WARNING - Working Folder!
Your working folder is not empty, click Show Working Folder to view its contents

Initializing nanddump1.bin, please wait...
Glitch2 selected
RGH3 selected
Nand Initialization Finished

XeLL image created

Checking Console...
Flash Config: 0x00023010

Writing glitch.ecc to Nand
PicoFlasher has encountered an error
Try to unplug and replug the device
System.IO.IOException
```

![image](https://github.com/user-attachments/assets/fa42fd4d-681d-48f6-842a-7be1e34968d3)

### System version

Windows 10 Home

### J-Runner version

3.3.0 r3

**Comment by Octal450** [comment]
This is a problem with the Pico firmware. It's buggy. I cannot solve it. Sorry.

Kind Regards,
Josh
