### ISSUE TITLE
Replace current kernel and xam to 17559 in older dash flash images to allow new game to work on old dashes

### ISSUE THREAD

**Issue by IcyModz420** [Octal450/J-Runner-with-Extras#63]
### Is your feature request related to a problem or missing feature? Please describe.

I believe it could be possible to replace xbkrnl.exe and xam.xex of older dashboards with a 17559 hacked kernel version and allow it to boot newer games while using older dashboards and launching games via xex menu at least if not regularly naturally replacing the kernel should also replace the hypervisor.. so with updated kernel + hypervisor + xam it should work right? can you confirm this I haven't tried it yet myself but I have a triple nand with external nand wires to test

### Describe the solution you'd like

.

**Comment by Octal450** [comment]
This is not the place for this. It is unlikely that this would work.
