### ISSUE TITLE
Bug: 13604 Kinect Dash not working with some RGH3

### ISSUE THREAD

**Issue by quimodotcom** [Octal450/J-Runner-with-Extras#64]
### Describe the bug

Tried downgrading to kinect dashboard but cannot boot anything except xell.

### To Reproduce

1. Have a Xbox 360 Slim Trinity (Mine is a trinity and have found some reddit threads with the same error and they had trinitys)
2. Open JRunner
3. Create XeBuild with Dash 13604
4. Run Xell from Eject
5. Flash new Nand
6. Black screen from reboot

### Expected Behavior

Fully Functioning Kinect Dash with RGH3

### System version

Windows n10

### J-Runner version

3.3.0

**Comment by Octal450** [comment]
Not a bug in the application itself, just a patch issue possibly a conflict. I'll note this as an issue but there's nothing I can do it about it in the application itself. I'd have to ask someone knowledgable about patches.

**Comment by quimodotcom** [comment]
update on this? dont know if theres an update to the patches or anyone i can ask about the patches and how to modify/fix them

**Comment by Octal450** [comment]
No update.
J

**Comment by quimodotcom** [comment]
Thought id leave a note here. Ive finally came back to my main xbox and tried 13604 again and same nothing burger.

Ive tried digging in the files and im not 100% but I believe the culprit is the patches_trinity.bin file. However need someone to confirm on other console types if 13604 works for them?

Thanks,
Evan.
