### ISSUE TITLE
Bug: Jrunner detects falcon 16mb as a falcon 64mb

### ISSUE THREAD

**Issue by quimodotcom** [Octal450/J-Runner-with-Extras#65]
### Describe the bug

I don't know whether this is a Jrunner issue or a jr programmer issue. But my console keeps detecting a 64mb console when it's a 16mb. Is there any way to prevent it from changing when I manually change the console type to 16mb.

Will provide logs or soldering pictures if requested.

### Expected Behavior

Jr programmer wires hooked up and Jrunner detects a falcon with 16mb and. Instead detects 64mb and starts reading a 64mb file from nand.

### System version

Windows 7 64-bit

### J-Runner version

Latest

**Comment by quimodotcom** [comment]
Just to add context that might help, this is a troublesome falcon. I got it a month ago and got to work reading the band, I then wiped my computer sometime after due to the windows image I had being very corrupt. I completely forgot to transfer the folder with my nand on it, leaving me with no CPU key or nand. I then followed a tutorial to get the CPU key then to create a donor nand. Flashed the donor nand, and now I get a mix of rrod 0001 and 1020. And now ofc, it reads falcon 64mb on Jrunner.

**Comment by Octal450** [comment]
What is the part number of your nand ?

**Comment by quimodotcom** [comment]
From what i can make out from the faded text. "HY27_808218__"

**Comment by quimodotcom** [comment]
_ meaning a character i cant make out

**Comment by Octal450** [comment]
What is the flash config reported by JRunner?

**Comment by quimodotcom** [comment]
Falcon 64mb

**Comment by Octal450** [comment]
No, the flash config in the console.

**Comment by quimodotcom** [comment]
Checking Console...
Version: 10
Flash Config: 0x01198030
Xenon, Zephyr, Falcon: 64MB
CB Version: 5772

**Comment by Octal450** [comment]
not bug in JR.
Your mb likely has damaged resistors for flash config.

**Comment by quimodotcom** [comment]
shit. thought so. would you think it would be a good idea to replace the nand chip

**Comment by Octal450** [comment]
Check the resistors. That the likely cause.

**Comment by quimodotcom** [comment]
would you know the exact ones? or just in general?

**Comment by Octal450** [comment]
![image](https://github.com/user-attachments/assets/ecd46d1c-e58a-486c-82d7-de4d20fd13b9)
Send pic.
