### ISSUE TITLE
OpenXenium CPLD flashing 

### ISSUE THREAD

**Issue by TheRealNextria** [Octal450/J-Runner-with-Extras#66]
### Describe the bug

Hello, 

I was trying out the CPLD flash function, but run into a error:

xFlasher: Flashing openxenium.svf via JTAG
xFlasher: SVF Flash Failed

i also have Xilinx Impact setup, and the chip programs and works without a problem.

Out of 3 chips i tried only one flashed without a problem, 
I checked the device ID and this is what i found.

White one:
'1': IDCODE is '00111001011000000100000010010011'
'1': IDCODE is '39604093' (in hex).
'1': : Manufacturer's ID = Xilinx xc9572xl, Version : 3

Purple one with dot:
'1': IDCODE is '00111001011000000100000010010011'
'1': IDCODE is '39604093' (in hex).
'1': : Manufacturer's ID = Xilinx xc9572xl, Version : 3

Purple one without dot:
'1': IDCODE is '01011001011000000100000010010011'
'1': IDCODE is '59604093' (in hex).
'1': : Manufacturer's ID = Xilinx xc9572xl, Version : 5		

Only version 5 programs, i dont know if J-runner is looking for the ID code "59604093" ?
If so could version 3, "39604093" also be added please ?
 		

### To Reproduce

Try to program version 5, works
Try to program version 3 does not work.

Both programm fine with Impact.

### Expected Behavior

To programm the chip

### System version

Windows 10

### J-Runner version

V3.3.0 r4:

**Comment by Octal450** [comment]
JRunner uses UrJtag (which is an awfully buggy program) for this.

Can you try to program it with the UrJtag copy (common/xflasher) manually and see what the result is?

The commands:
cable ft2232
detect
svf CompletePathNoSpaces progress

CompletePathNoSpaces must be the path to the svf which cannot have any spaces. So do like C:\openxenium.svf

Kind Regards,
Josh

**Comment by TheRealNextria** [comment]
Hello,

I tried it, i get the following

`jtag> cable ft2232
Connected to libftd2xx driver.
jtag> detect
IR length: 8
Chain length: 1
Device Id: 00111001011000000100000010010011 (0x0000000039604093)
  Manufacturer: Xilinx
  Part(0):         XC9572XL-VQ64
  Unknown stepping!
chain.c(149) Part 0 without active instruction
chain.c(200) Part 0 without active instruction
chain.c(149) Part 0 without active instruction
jtag> svf C:\Users\bosro\Desktop\J-Runner-with-Extras\common\svf\openxenium.svf
Error svf: could not establish SIR instruction`

I was looking online and tried to add the device ID to the PARTS file in the xilinx directory 

`1001011000000100	xc9572xl-vq64   XC9572XL-VQ64`

and the bits to the STEPPING file in the xc9572xl-vq64 directory

`0011	xc9572xl-vq64 1`

I get a lot of error, but it will now flash, and works :)

**Comment by Octal450** [comment]
Thank you.
Release updated.

Kind Regards,
Josh

**Comment by TheRealNextria** [comment]
Hello Josh,

Could you also add the following to the stepping file, for V4 CPLD chips ?

0100	xc9572xl-vq64 1

Regards

Nextria
