### ISSUE TITLE
Bug: <title>Unhandled Exception: <ISD Sound Editor>

### ISSUE THREAD

**Issue by jacobb740** [Octal450/J-Runner-with-Extras#67]
### Describe the bug

When i go to open ISD Sound Editor a window pops up saying "Unhandled exception has occurred in your application." If i click continue every button is greyed out and wont work.

### Expected Behavior

I expected ISD Sound Editor to open and the buttons able to press.

### System version

windows 10 64 bit

### J-Runner version

3.3.0 r4

**Comment by Octal450** [comment]
Works for me. Please use Restore Files option to fix your install.

**Comment by jacobb740** [comment]
The restore files option didn't help it's still popping up.
