### ISSUE TITLE
Forecast to implement XONE HDD function again? - 

### ISSUE THREAD

**Issue by MSXCelulares** [Octal450/J-Runner-with-Extras#9]
Hello, I would like to leave with a suggestion, the re-introduction of the HDD XONE function in JRunner with Extras, because here in my region I have done many repairs and replacements of HDD in XONE. Thank you friends, success always.

**Comment by Octal450** [comment]
I wasn't aware anyone still used it. Ok, will do. A patch update will be released soon.

Kind Regards,
Josh

**Comment by Octal450** [comment]
More likely I will separate the functionality out as a separate program. The HDD program has nothing in common with the rest of JR.

Kind Regards,
Josh

**Comment by Octal450** [comment]
I will add a new program for it @MSXCelulares and comment here :)
Josh
